theme: jekyll-theme-slate
baseurl: ""  # Pusta, jeśli strona jest w katalogu głównym repozytorium
url: "https://alienanietka.github.io"  # Twój URL strony

navigation:
  - title: "Home"
    url: "/"
  - title: "News"
    url: "/news/"
  - title: "Group"
    url: "/group/"
  - title: "Research"
    url: "/research/"
  - title: "Women in Science"
    url: "/women-in-science/"
  - title: "Books for Children"
    url: "/books-for-children/"
  - title: "Positions"
    url: "/positions/"
